spring.application.name=JobTrakrr
spring.datasource.url=jdbc:postgresql://localhost:5432/jobtrakrr
spring.datasource.username=postgres
spring.datasource.password=NinayJain
spring.jpa.hibernate.ddl-auto=update