spring.application.name=JobTrakrr
spring.datasource.url=jdbc:postgresql://localhost:5432/jobtrakrr
spring.datasource.username=Your Username
spring.datasource.password=YourPassword
spring.jpa.hibernate.ddl-auto=update
